import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Heart, ShieldCheck, Star } from "@phosphor-icons/react/dist/ssr";
import { ArtworkCard } from "@/components/artwork-card";
import { StatusPill } from "@/components/status-pill";
import { artists, getArtist, getArtistArt, services } from "@/data/mock-data";

export function generateStaticParams() { return artists.map((artist) => ({ id: artist.id })); }

export default async function ArtistProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const artist = getArtist(id);
  if (!artist) notFound();
  const portfolio = getArtistArt(id);
  const artistServices = services.filter((service) => service.artistId === id);
  return <div>
    <section className="border-b border-black/5 bg-[#f3efe8]"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-16"><div className="flex flex-col items-center text-center sm:flex-row sm:items-start sm:text-left"><Image src={artist.avatar} alt={`${artist.displayName} avatar`} width={144} height={144} className="size-28 rounded-[2rem] object-cover ring-4 ring-white sm:size-36" /><div className="mt-5 flex-1 sm:ml-7 sm:mt-0"><div className="flex flex-wrap items-center justify-center gap-2 sm:justify-start"><h1 className="text-3xl font-bold tracking-tight">@{artist.username}</h1>{artist.accountType === "protected-teen" && <span className="inline-flex items-center gap-1 rounded-full bg-white px-2.5 py-1 text-xs font-bold text-plum"><ShieldCheck size={15} weight="fill" />Parent supported</span>}</div><p className="mt-1 text-lg text-black/60">{artist.specialty}</p><p className="mt-4 max-w-xl leading-7 text-black/65">{artist.bio}</p><div className="mt-5 flex flex-wrap justify-center gap-x-5 gap-y-2 text-sm sm:justify-start"><span className="flex items-center gap-1 font-bold"><Star size={16} weight="fill" className="text-amber-400" />{artist.rating} rating</span><span><strong>{artist.completedCommissions}</strong> completed</span><StatusPill status={artist.availability} slots={artist.slots} /></div></div><div className="mt-6 flex w-full gap-2 sm:mt-0 sm:w-auto"><button className="flex-1 rounded-full border border-black/10 bg-white px-5 py-3 text-sm font-bold sm:flex-none"><Heart className="inline" size={18} /> Save</button><button className="flex-1 rounded-full bg-ink px-5 py-3 text-sm font-bold text-white sm:flex-none">Request art</button></div></div></div></section>
    <div className="sticky top-16 z-30 border-b border-black/5 bg-paper/95 backdrop-blur"><div className="no-scrollbar mx-auto flex max-w-6xl gap-7 overflow-x-auto px-4 sm:px-6">{["Portfolio", "Posts", "Commissions", "Reviews", "About & rules"].map((tab, i) => <button key={tab} className={`whitespace-nowrap border-b-2 py-4 text-sm font-bold ${i === 0 ? "border-ink text-ink" : "border-transparent text-black/45"}`}>{tab}</button>)}</div></div>
    <section className="mx-auto grid max-w-6xl gap-10 px-4 py-10 sm:px-6 lg:grid-cols-[1fr_340px]"><div><h2 className="font-[family-name:var(--font-display)] text-4xl">Selected work</h2>{portfolio.length ? <div className="mt-6 columns-2 gap-4">{portfolio.map((artwork) => <ArtworkCard key={artwork.id} artwork={artwork} artist={artist} />)}</div> : <p className="mt-6 rounded-3xl bg-white p-10 text-center text-black/50">More portfolio work is coming soon.</p>}</div><aside><div className="rounded-3xl border border-black/[0.07] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Commission services</h2><StatusPill status={artist.availability} /></div>{artistServices.length ? <div className="mt-3 divide-y divide-black/[0.07]">{artistServices.map((service) => <Link href={`/commissions/${service.id}`} key={service.id} className="block py-4"><h3 className="font-bold">{service.title}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 text-black/50">{service.description}</p><div className="mt-3 flex items-center justify-between text-sm"><span className="text-black/45">{service.turnaround}</span><strong>From ${service.startingPrice}</strong></div></Link>)}</div> : <div className="py-8 text-center text-sm text-black/45">No active services right now.</div>}<button disabled={artist.availability === "closed"} className="mt-3 w-full rounded-full bg-plum px-5 py-3 text-sm font-bold text-white disabled:bg-black/10 disabled:text-black/35">{artist.availability === "waitlist" ? "Join waitlist" : artist.availability === "closed" ? "Commissions closed" : "Request commission"}</button></div>{artist.accountType === "protected-teen" && <div className="mt-4 rounded-3xl bg-mist p-5 text-sm leading-6 text-black/60"><ShieldCheck size={22} weight="fill" className="mb-2 text-plum" /><strong className="block text-ink">Protected teen account</strong>Communication stays inside Arya, and parent approval is used for commission actions.</div>}</aside></section>
  </div>;
}
